# Build Corne with nice_nano (full size working firmware)
name: 'Build Corne nice_nano'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left", "corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      layers: '["default"]'
      mapping: '["default"]'
      custom_config: '["default"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_EXT_POWER=y\nCONFIG_ZMK_SLEEP=n\nCONFIG_ZMK_PM_SOFT_OFF=y\nCONFIG_ZMK_IDLE_TIMEOUT=30000\nCONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y\nCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=n\nCONFIG_ZMK_WIDGET_WPM_STATUS=y"]'
      branches: '["default"]'
      modules: '["default"]'
      
